version: '3.8'

services:
  zookeeper1:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      # --- aquí definimos el ensemble ---
      ZOOKEEPER_SERVER_1: zookeeper1:2888:3888
      ZOOKEEPER_SERVER_2: zookeeper2:2888:3888
      ZOOKEEPER_SERVER_3: zookeeper3:2888:3888
    ports:
      - "2181:2181"
      # expón también los puertos de quorum si quieres inspeccionarlos desde fuera:
      - "2888:2888"
      - "3888:3888"
    networks:
      - kafka-net

  zookeeper2:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVER_1: zookeeper1:2888:3888
      ZOOKEEPER_SERVER_2: zookeeper2:2888:3888
      ZOOKEEPER_SERVER_3: zookeeper3:2888:3888
    ports:
      - "2182:2181"
      - "2889:2888"
      - "3889:3888"
    networks:
      - kafka-net

  zookeeper3:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVER_1: zookeeper1:2888:3888
      ZOOKEEPER_SERVER_2: zookeeper2:2888:3888
      ZOOKEEPER_SERVER_3: zookeeper3:2888:3888
    ports:
      - "2183:2181"
      - "2890:2888"
      - "3890:3888"
    networks:
      - kafka-net
  kafka1:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    networks:
      - kafka-net

  kafka2:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    ports:
      - "9093:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    networks:
      - kafka-net

  kafka3:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    ports:
      - "9094:9092"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    networks:
      - kafka-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: kafka-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9092,kafka2:9092,kafka3:9092
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge
