version: '3.8'

services:
  ms-ventas:
    build:
      context: ./ms-ventas
      dockerfile: Dockerfile
    image: ms-ventas:latest
    container_name: ms-ventas
    ports:
      - "8081:8081"
    networks:
      - comercio-net

  comercio:
    build:
      context: ./comercio
      dockerfile: Dockerfile
    image: comercio:latest
    container_name: comercio
    ports:
      - "8080:8080"
    environment:
      MS_VENTAS_URL: "http://ms-ventas:8081"
    depends_on:
      - ms-ventas
    networks:
      - comercio-net

networks:
  comercio-net:
    driver: bridge